# Generated by Django 4.0.5 on 2022-08-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_mascota', models.CharField(max_length=200, verbose_name='Nombde de la Mascota')),
                ('Edad', models.CharField(max_length=10, verbose_name='Edad')),
                ('Porte', models.CharField(max_length=50, verbose_name='Porte')),
                ('Raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('Datos_adicionales', models.CharField(max_length=300, verbose_name='Datos adicionales')),
                ('Datos_persona', models.CharField(max_length=300, verbose_name='Datos de la persona')),
                ('Direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('Telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
    ]
