# Generated by Django 4.0.5 on 2022-08-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopciones',
            name='Nombre_mascota',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Mascota'),
        ),
        migrations.AlterField(
            model_name='adopciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
